package com.ctgu.bean;

import java.util.Date;

public class Articles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.APosttime
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Date aposttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.AContent
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String acontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.ATitle
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String atitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.AClickRate
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Float aclickrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.AType
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String atype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.AUpCounts
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer aupcounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.AStatus
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String astatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Articles.Users_UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer usersUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.AID
     *
     * @return the value of Articles.AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.AID
     *
     * @param aid the value for Articles.AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.APosttime
     *
     * @return the value of Articles.APosttime
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Date getAposttime() {
        return aposttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.APosttime
     *
     * @param aposttime the value for Articles.APosttime
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAposttime(Date aposttime) {
        this.aposttime = aposttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.AContent
     *
     * @return the value of Articles.AContent
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getAcontent() {
        return acontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.AContent
     *
     * @param acontent the value for Articles.AContent
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAcontent(String acontent) {
        this.acontent = acontent == null ? null : acontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.ATitle
     *
     * @return the value of Articles.ATitle
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getAtitle() {
        return atitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.ATitle
     *
     * @param atitle the value for Articles.ATitle
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAtitle(String atitle) {
        this.atitle = atitle == null ? null : atitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.AClickRate
     *
     * @return the value of Articles.AClickRate
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Float getAclickrate() {
        return aclickrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.AClickRate
     *
     * @param aclickrate the value for Articles.AClickRate
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAclickrate(Float aclickrate) {
        this.aclickrate = aclickrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.AType
     *
     * @return the value of Articles.AType
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getAtype() {
        return atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.AType
     *
     * @param atype the value for Articles.AType
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAtype(String atype) {
        this.atype = atype == null ? null : atype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.AUpCounts
     *
     * @return the value of Articles.AUpCounts
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getAupcounts() {
        return aupcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.AUpCounts
     *
     * @param aupcounts the value for Articles.AUpCounts
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAupcounts(Integer aupcounts) {
        this.aupcounts = aupcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.AStatus
     *
     * @return the value of Articles.AStatus
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getAstatus() {
        return astatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.AStatus
     *
     * @param astatus the value for Articles.AStatus
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setAstatus(String astatus) {
        this.astatus = astatus == null ? null : astatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Articles.Users_UID
     *
     * @return the value of Articles.Users_UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getUsersUid() {
        return usersUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Articles.Users_UID
     *
     * @param usersUid the value for Articles.Users_UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUsersUid(Integer usersUid) {
        this.usersUid = usersUid;
    }
}