package com.ctgu.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ArticlesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public ArticlesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAidIsNull() {
            addCriterion("AID is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("AID is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(Integer value) {
            addCriterion("AID =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(Integer value) {
            addCriterion("AID <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(Integer value) {
            addCriterion("AID >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(Integer value) {
            addCriterion("AID >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(Integer value) {
            addCriterion("AID <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(Integer value) {
            addCriterion("AID <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<Integer> values) {
            addCriterion("AID in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<Integer> values) {
            addCriterion("AID not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(Integer value1, Integer value2) {
            addCriterion("AID between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(Integer value1, Integer value2) {
            addCriterion("AID not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAposttimeIsNull() {
            addCriterion("APosttime is null");
            return (Criteria) this;
        }

        public Criteria andAposttimeIsNotNull() {
            addCriterion("APosttime is not null");
            return (Criteria) this;
        }

        public Criteria andAposttimeEqualTo(Date value) {
            addCriterionForJDBCDate("APosttime =", value, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("APosttime <>", value, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeGreaterThan(Date value) {
            addCriterionForJDBCDate("APosttime >", value, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APosttime >=", value, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeLessThan(Date value) {
            addCriterionForJDBCDate("APosttime <", value, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APosttime <=", value, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeIn(List<Date> values) {
            addCriterionForJDBCDate("APosttime in", values, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("APosttime not in", values, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APosttime between", value1, value2, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAposttimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APosttime not between", value1, value2, "aposttime");
            return (Criteria) this;
        }

        public Criteria andAcontentIsNull() {
            addCriterion("AContent is null");
            return (Criteria) this;
        }

        public Criteria andAcontentIsNotNull() {
            addCriterion("AContent is not null");
            return (Criteria) this;
        }

        public Criteria andAcontentEqualTo(String value) {
            addCriterion("AContent =", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentNotEqualTo(String value) {
            addCriterion("AContent <>", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentGreaterThan(String value) {
            addCriterion("AContent >", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentGreaterThanOrEqualTo(String value) {
            addCriterion("AContent >=", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentLessThan(String value) {
            addCriterion("AContent <", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentLessThanOrEqualTo(String value) {
            addCriterion("AContent <=", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentLike(String value) {
            addCriterion("AContent like", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentNotLike(String value) {
            addCriterion("AContent not like", value, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentIn(List<String> values) {
            addCriterion("AContent in", values, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentNotIn(List<String> values) {
            addCriterion("AContent not in", values, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentBetween(String value1, String value2) {
            addCriterion("AContent between", value1, value2, "acontent");
            return (Criteria) this;
        }

        public Criteria andAcontentNotBetween(String value1, String value2) {
            addCriterion("AContent not between", value1, value2, "acontent");
            return (Criteria) this;
        }

        public Criteria andAtitleIsNull() {
            addCriterion("ATitle is null");
            return (Criteria) this;
        }

        public Criteria andAtitleIsNotNull() {
            addCriterion("ATitle is not null");
            return (Criteria) this;
        }

        public Criteria andAtitleEqualTo(String value) {
            addCriterion("ATitle =", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleNotEqualTo(String value) {
            addCriterion("ATitle <>", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleGreaterThan(String value) {
            addCriterion("ATitle >", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleGreaterThanOrEqualTo(String value) {
            addCriterion("ATitle >=", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleLessThan(String value) {
            addCriterion("ATitle <", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleLessThanOrEqualTo(String value) {
            addCriterion("ATitle <=", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleLike(String value) {
            addCriterion("ATitle like", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleNotLike(String value) {
            addCriterion("ATitle not like", value, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleIn(List<String> values) {
            addCriterion("ATitle in", values, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleNotIn(List<String> values) {
            addCriterion("ATitle not in", values, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleBetween(String value1, String value2) {
            addCriterion("ATitle between", value1, value2, "atitle");
            return (Criteria) this;
        }

        public Criteria andAtitleNotBetween(String value1, String value2) {
            addCriterion("ATitle not between", value1, value2, "atitle");
            return (Criteria) this;
        }

        public Criteria andAclickrateIsNull() {
            addCriterion("AClickRate is null");
            return (Criteria) this;
        }

        public Criteria andAclickrateIsNotNull() {
            addCriterion("AClickRate is not null");
            return (Criteria) this;
        }

        public Criteria andAclickrateEqualTo(Float value) {
            addCriterion("AClickRate =", value, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateNotEqualTo(Float value) {
            addCriterion("AClickRate <>", value, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateGreaterThan(Float value) {
            addCriterion("AClickRate >", value, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateGreaterThanOrEqualTo(Float value) {
            addCriterion("AClickRate >=", value, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateLessThan(Float value) {
            addCriterion("AClickRate <", value, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateLessThanOrEqualTo(Float value) {
            addCriterion("AClickRate <=", value, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateIn(List<Float> values) {
            addCriterion("AClickRate in", values, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateNotIn(List<Float> values) {
            addCriterion("AClickRate not in", values, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateBetween(Float value1, Float value2) {
            addCriterion("AClickRate between", value1, value2, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAclickrateNotBetween(Float value1, Float value2) {
            addCriterion("AClickRate not between", value1, value2, "aclickrate");
            return (Criteria) this;
        }

        public Criteria andAtypeIsNull() {
            addCriterion("AType is null");
            return (Criteria) this;
        }

        public Criteria andAtypeIsNotNull() {
            addCriterion("AType is not null");
            return (Criteria) this;
        }

        public Criteria andAtypeEqualTo(String value) {
            addCriterion("AType =", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeNotEqualTo(String value) {
            addCriterion("AType <>", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeGreaterThan(String value) {
            addCriterion("AType >", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeGreaterThanOrEqualTo(String value) {
            addCriterion("AType >=", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeLessThan(String value) {
            addCriterion("AType <", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeLessThanOrEqualTo(String value) {
            addCriterion("AType <=", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeLike(String value) {
            addCriterion("AType like", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeNotLike(String value) {
            addCriterion("AType not like", value, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeIn(List<String> values) {
            addCriterion("AType in", values, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeNotIn(List<String> values) {
            addCriterion("AType not in", values, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeBetween(String value1, String value2) {
            addCriterion("AType between", value1, value2, "atype");
            return (Criteria) this;
        }

        public Criteria andAtypeNotBetween(String value1, String value2) {
            addCriterion("AType not between", value1, value2, "atype");
            return (Criteria) this;
        }

        public Criteria andAupcountsIsNull() {
            addCriterion("AUpCounts is null");
            return (Criteria) this;
        }

        public Criteria andAupcountsIsNotNull() {
            addCriterion("AUpCounts is not null");
            return (Criteria) this;
        }

        public Criteria andAupcountsEqualTo(Integer value) {
            addCriterion("AUpCounts =", value, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsNotEqualTo(Integer value) {
            addCriterion("AUpCounts <>", value, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsGreaterThan(Integer value) {
            addCriterion("AUpCounts >", value, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUpCounts >=", value, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsLessThan(Integer value) {
            addCriterion("AUpCounts <", value, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsLessThanOrEqualTo(Integer value) {
            addCriterion("AUpCounts <=", value, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsIn(List<Integer> values) {
            addCriterion("AUpCounts in", values, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsNotIn(List<Integer> values) {
            addCriterion("AUpCounts not in", values, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsBetween(Integer value1, Integer value2) {
            addCriterion("AUpCounts between", value1, value2, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAupcountsNotBetween(Integer value1, Integer value2) {
            addCriterion("AUpCounts not between", value1, value2, "aupcounts");
            return (Criteria) this;
        }

        public Criteria andAstatusIsNull() {
            addCriterion("AStatus is null");
            return (Criteria) this;
        }

        public Criteria andAstatusIsNotNull() {
            addCriterion("AStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAstatusEqualTo(String value) {
            addCriterion("AStatus =", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusNotEqualTo(String value) {
            addCriterion("AStatus <>", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusGreaterThan(String value) {
            addCriterion("AStatus >", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusGreaterThanOrEqualTo(String value) {
            addCriterion("AStatus >=", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusLessThan(String value) {
            addCriterion("AStatus <", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusLessThanOrEqualTo(String value) {
            addCriterion("AStatus <=", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusLike(String value) {
            addCriterion("AStatus like", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusNotLike(String value) {
            addCriterion("AStatus not like", value, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusIn(List<String> values) {
            addCriterion("AStatus in", values, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusNotIn(List<String> values) {
            addCriterion("AStatus not in", values, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusBetween(String value1, String value2) {
            addCriterion("AStatus between", value1, value2, "astatus");
            return (Criteria) this;
        }

        public Criteria andAstatusNotBetween(String value1, String value2) {
            addCriterion("AStatus not between", value1, value2, "astatus");
            return (Criteria) this;
        }

        public Criteria andUsersUidIsNull() {
            addCriterion("Users_UID is null");
            return (Criteria) this;
        }

        public Criteria andUsersUidIsNotNull() {
            addCriterion("Users_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUsersUidEqualTo(Integer value) {
            addCriterion("Users_UID =", value, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidNotEqualTo(Integer value) {
            addCriterion("Users_UID <>", value, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidGreaterThan(Integer value) {
            addCriterion("Users_UID >", value, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Users_UID >=", value, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidLessThan(Integer value) {
            addCriterion("Users_UID <", value, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidLessThanOrEqualTo(Integer value) {
            addCriterion("Users_UID <=", value, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidIn(List<Integer> values) {
            addCriterion("Users_UID in", values, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidNotIn(List<Integer> values) {
            addCriterion("Users_UID not in", values, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidBetween(Integer value1, Integer value2) {
            addCriterion("Users_UID between", value1, value2, "usersUid");
            return (Criteria) this;
        }

        public Criteria andUsersUidNotBetween(Integer value1, Integer value2) {
            addCriterion("Users_UID not between", value1, value2, "usersUid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Articles
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 20 04:55:17 PST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}