package com.ctgu.bean;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comments.CID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comments.Users_UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer usersUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comments.Articles_AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer articlesAid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comments.CPostTime
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Date cposttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comments.CUpCounts
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer cupcounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Comments.CContent
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String ccontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.CID
     *
     * @return the value of Comments.CID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.CID
     *
     * @param cid the value for Comments.CID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.Users_UID
     *
     * @return the value of Comments.Users_UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getUsersUid() {
        return usersUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.Users_UID
     *
     * @param usersUid the value for Comments.Users_UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUsersUid(Integer usersUid) {
        this.usersUid = usersUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.Articles_AID
     *
     * @return the value of Comments.Articles_AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getArticlesAid() {
        return articlesAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.Articles_AID
     *
     * @param articlesAid the value for Comments.Articles_AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setArticlesAid(Integer articlesAid) {
        this.articlesAid = articlesAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.CPostTime
     *
     * @return the value of Comments.CPostTime
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Date getCposttime() {
        return cposttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.CPostTime
     *
     * @param cposttime the value for Comments.CPostTime
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setCposttime(Date cposttime) {
        this.cposttime = cposttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.CUpCounts
     *
     * @return the value of Comments.CUpCounts
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getCupcounts() {
        return cupcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.CUpCounts
     *
     * @param cupcounts the value for Comments.CUpCounts
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setCupcounts(Integer cupcounts) {
        this.cupcounts = cupcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.CContent
     *
     * @return the value of Comments.CContent
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getCcontent() {
        return ccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.CContent
     *
     * @param ccontent the value for Comments.CContent
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setCcontent(String ccontent) {
        this.ccontent = ccontent == null ? null : ccontent.trim();
    }
}