package com.ctgu.bean;

public class Resourses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Resourses.RID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Resourses.RName
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String rname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Resourses.RPath
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String rpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Resourses.RType
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String rtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Resourses.RStatus
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String rstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Resourses.Articles_AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer articlesAid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Resourses.RID
     *
     * @return the value of Resourses.RID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Resourses.RID
     *
     * @param rid the value for Resourses.RID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Resourses.RName
     *
     * @return the value of Resourses.RName
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Resourses.RName
     *
     * @param rname the value for Resourses.RName
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Resourses.RPath
     *
     * @return the value of Resourses.RPath
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getRpath() {
        return rpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Resourses.RPath
     *
     * @param rpath the value for Resourses.RPath
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setRpath(String rpath) {
        this.rpath = rpath == null ? null : rpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Resourses.RType
     *
     * @return the value of Resourses.RType
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getRtype() {
        return rtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Resourses.RType
     *
     * @param rtype the value for Resourses.RType
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setRtype(String rtype) {
        this.rtype = rtype == null ? null : rtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Resourses.RStatus
     *
     * @return the value of Resourses.RStatus
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getRstatus() {
        return rstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Resourses.RStatus
     *
     * @param rstatus the value for Resourses.RStatus
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setRstatus(String rstatus) {
        this.rstatus = rstatus == null ? null : rstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Resourses.Articles_AID
     *
     * @return the value of Resourses.Articles_AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getArticlesAid() {
        return articlesAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Resourses.Articles_AID
     *
     * @param articlesAid the value for Resourses.Articles_AID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setArticlesAid(Integer articlesAid) {
        this.articlesAid = articlesAid;
    }
}