package com.ctgu.bean;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UName
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UPassword
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String upassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UEmail
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String uemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UBirthday
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Date ubirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UHead
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private String uhead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.USex
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer usex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UGrade
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer ugrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.UClass
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    private Integer uclass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UID
     *
     * @return the value of Users.UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UID
     *
     * @param uid the value for Users.UID
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UName
     *
     * @return the value of Users.UName
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UName
     *
     * @param uname the value for Users.UName
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UPassword
     *
     * @return the value of Users.UPassword
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UPassword
     *
     * @param upassword the value for Users.UPassword
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UEmail
     *
     * @return the value of Users.UEmail
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UEmail
     *
     * @param uemail the value for Users.UEmail
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UBirthday
     *
     * @return the value of Users.UBirthday
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Date getUbirthday() {
        return ubirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UBirthday
     *
     * @param ubirthday the value for Users.UBirthday
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUbirthday(Date ubirthday) {
        this.ubirthday = ubirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UHead
     *
     * @return the value of Users.UHead
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public String getUhead() {
        return uhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UHead
     *
     * @param uhead the value for Users.UHead
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUhead(String uhead) {
        this.uhead = uhead == null ? null : uhead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.USex
     *
     * @return the value of Users.USex
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.USex
     *
     * @param usex the value for Users.USex
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUsex(Integer usex) {
        this.usex = usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UGrade
     *
     * @return the value of Users.UGrade
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getUgrade() {
        return ugrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UGrade
     *
     * @param ugrade the value for Users.UGrade
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUgrade(Integer ugrade) {
        this.ugrade = ugrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.UClass
     *
     * @return the value of Users.UClass
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public Integer getUclass() {
        return uclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.UClass
     *
     * @param uclass the value for Users.UClass
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    public void setUclass(Integer uclass) {
        this.uclass = uclass;
    }
}