package com.ctgu.dao;

import com.ctgu.bean.Articles;
import com.ctgu.bean.ArticlesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    long countByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int deleteByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int insert(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int insertSelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    List<Articles> selectByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    Articles selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByExampleSelective(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByExample(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByPrimaryKeySelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Articles
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByPrimaryKey(Articles record);
}