package com.ctgu.dao;

import com.ctgu.bean.Comments;
import com.ctgu.bean.CommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    long countByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int deleteByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    List<Comments> selectByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    Comments selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByExampleSelective(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByExample(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comments
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByPrimaryKey(Comments record);
}