package com.ctgu.dao;

import com.ctgu.bean.Resourses;
import com.ctgu.bean.ResoursesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResoursesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    long countByExample(ResoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int deleteByExample(ResoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int insert(Resourses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int insertSelective(Resourses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    List<Resourses> selectByExample(ResoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    Resourses selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByExampleSelective(@Param("record") Resourses record, @Param("example") ResoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByExample(@Param("record") Resourses record, @Param("example") ResoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByPrimaryKeySelective(Resourses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resourses
     *
     * @mbg.generated Thu Dec 20 04:55:17 PST 2018
     */
    int updateByPrimaryKey(Resourses record);
}